# Central Mapping File for Ledger Master (MongoDB -> Tally Canonical Model -> XML Tags)

LEDGER_MAPPING = [
    {
        "formField": "Ledger Name",
        "mongoField": "ledgerName",
        "tallyField": "ledgerName",
        "xmlTag": "NAME",
        "section": "LEDGER",
        "type": "string",
        "required": True,
        "transform": "string",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "Group",
        "mongoField": "groupName",
        "tallyField": "parentGroupName",
        "xmlTag": "PARENT",
        "section": "LEDGER",
        "type": "string",
        "required": True,
        "transform": "string",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "Opening Balance",
        "mongoField": "balances.openingBalance.amount",
        "tallyField": "openingBalance",
        "xmlTag": "OPENINGBALANCE",
        "section": "LEDGER",
        "type": "number",
        "required": False,
        "transform": "openingBalance",
        "condition": "if_nonzero",
        "status": "VERIFIED"
    },
    {
        "formField": "Opening Balance Type",
        "mongoField": "balances.openingBalance.type",
        "tallyField": "isDeemedPositive",
        "xmlTag": "ISDEEMEDPOSITIVE",
        "section": "LEDGER",
        "type": "string",
        "required": False,
        "transform": "deemedPositive",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "PAN Number",
        "mongoField": "partyDetails.panNumber",
        "tallyField": "pan",
        "xmlTag": "PANNUMBER",
        "section": "GST/PARTY",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "GSTIN",
        "mongoField": "partyDetails.gstin",
        "tallyField": "gstin",
        "xmlTag": "PARTYGSTIN",
        "section": "GST",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "State",
        "mongoField": "partyDetails.gstState",
        "tallyField": "state",
        "xmlTag": "STATENAME",
        "section": "ADDRESS/GST",
        "type": "string",
        "required": False,
        "transform": "state",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "PIN Code",
        "mongoField": "partyDetails.pinCode",
        "tallyField": "pincode",
        "xmlTag": "PINCODE",
        "section": "ADDRESS",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "Phone",
        "mongoField": "partyDetails.phone",
        "tallyField": "phone",
        "xmlTag": "PHONE",
        "section": "CONTACT",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "Mobile",
        "mongoField": "partyDetails.mobile",
        "tallyField": "mobile",
        "xmlTag": "MOBILE",
        "section": "CONTACT",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "Email",
        "mongoField": "partyDetails.email",
        "tallyField": "email",
        "xmlTag": "EMAIL",
        "section": "CONTACT",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "GST Registration Type",
        "mongoField": "partyDetails.gstRegistrationType",
        "tallyField": "registrationType",
        "xmlTag": "GSTREGISTRATIONTYPE",
        "section": "GST",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "GST Type of Supply",
        "mongoField": "taxDetails.gstTypeOfSupply",
        "tallyField": "natureOfSupply",
        "xmlTag": "GSTNATUREOFSUPPLY",
        "section": "GST",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "always",
        "status": "VERIFIED",
        "nilable": True
    },
    {
        "formField": "GST Duty Head",
        "mongoField": "taxDetails.gstDutyHead",
        "tallyField": "dutyHead",
        "xmlTag": "GSTDUTYHEAD",
        "section": "GST",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "always",
        "status": "VERIFIED",
        "nilable": True
    },
    {
        "formField": "Tax Type",
        "mongoField": "taxDetails.taxType",
        "tallyField": "taxType",
        "xmlTag": "TAXTYPE",
        "section": "GST",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "GST Rate",
        "mongoField": "taxDetails.gstRate",
        "tallyField": "gstRate",
        "xmlTag": "RATEOFTAXCALCULATION",
        "section": "GST",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "always",
        "status": "VERIFIED",
        "nilable": True
    },
    {
        "formField": "Bank Name",
        "mongoField": "bankDetails.bankName",
        "tallyField": "bankName",
        "xmlTag": "BANKNAME",
        "section": "BANK",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "Branch Name",
        "mongoField": "bankDetails.branchName",
        "tallyField": "branch",
        "xmlTag": "BRANCHNAME",
        "section": "BANK",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "Account Number",
        "mongoField": "bankDetails.accountNumber",
        "tallyField": "accountNumber",
        "xmlTag": "ACCOUNTNUMBER",
        "section": "BANK",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "IFSC",
        "mongoField": "bankDetails.ifscCode",
        "tallyField": "ifsc",
        "xmlTag": "IFSCCODE",
        "section": "BANK",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "SWIFT",
        "mongoField": "bankDetails.swiftCode",
        "tallyField": "swift",
        "xmlTag": "SWIFTCODE",
        "section": "BANK",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "UPI / VPA",
        "mongoField": "bankDetails.virtualPaymentAddress",
        "tallyField": "upi",
        "xmlTag": "SWIFTCODE",
        "section": "BANK",
        "type": "string",
        "required": False,
        "transform": "string",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "Address",
        "mongoField": "partyDetails.address",
        "tallyField": "address",
        "xmlTag": "ADDRESS.LIST",
        "section": "ADDRESS",
        "type": "list",
        "required": False,
        "transform": "address",
        "condition": "if_exists",
        "status": "VERIFIED"
    },
    {
        "formField": "Bill Wise",
        "mongoField": "flags.isBillWiseOn",
        "tallyField": "billWise",
        "xmlTag": "ISBILLWISEON",
        "section": "CONFIG",
        "type": "boolean",
        "required": False,
        "transform": "boolean",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "Cost Centre",
        "mongoField": "flags.isCostCentresOn",
        "tallyField": "costCentre",
        "xmlTag": "ISCOSTCENTRESON",
        "section": "CONFIG",
        "type": "boolean",
        "required": False,
        "transform": "boolean",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "Affects Stock",
        "mongoField": "flags.affectsStock",
        "tallyField": "affectsStock",
        "xmlTag": "AFFECTSSTOCK",
        "section": "CONFIG",
        "type": "boolean",
        "required": False,
        "transform": "boolean",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "Payroll",
        "mongoField": "flags.forPayroll",
        "tallyField": "payroll",
        "xmlTag": "FORPAYROLL",
        "section": "CONFIG",
        "type": "boolean",
        "required": False,
        "transform": "boolean",
        "condition": "always",
        "status": "VERIFIED"
    },
    {
        "formField": "Interest",
        "mongoField": "flags.isInterestOn",
        "tallyField": "interest",
        "xmlTag": "ISINTERESTON",
        "section": "CONFIG",
        "type": "boolean",
        "required": False,
        "transform": "boolean",
        "condition": "always",
        "status": "VERIFIED"
    }
]
